[phases.setup]
nixPkgs = ["python312", "pip", "playwright-driver"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install", "playwright install-deps"]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 30"