[phases.setup]
nixPkgs = ["python312", "playwright-driver"]

[phases.install]
cmds = [
	"python3 -m venv /opt/venv",
	"/opt/venv/bin/pip install --upgrade pip",
	"/opt/venv/bin/pip install -r requirements.txt",
	"/opt/venv/bin/playwright install",
	"/opt/venv/bin/playwright install-deps"
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 30"