[phases.setup]
nixPkgs = ["python312", "playwright-driver"]

[phases.install]
cmds = [
	"python3 -m venv .venv",
	"source /.venv/bin/activate",
	"python -m pip install -r requirements.txt",
	"python -m playwright install",
	"python -m playwright install-deps"
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 30"